### PR TITLE
Added amp_img filter

### PR DESCRIPTION
**Pull request by lcmartinezdev**
Hi, i added a filter to change img tags in html code.

### CODE REVIEW

**Comment by shtalinberg** [comment]
Please, add usage example to  tag description

**Comment by MaZZly** [comment]
A note: `<amp-img>` requires a closing `</amp-img>` tag as well as a `layout=""`, `height=""` and `width=""` attributes..

**Comment by CARocha** [comment]
yes this filter not working well the tag amp-img need closed
any people convert this with any trick? i try use bs4 for this task but not working well :(

Cheers

**Comment by lcmartinezdev** [comment]
@CARocha I going to review that, ty

**Pull request merged**
